import type { ReactNode } from "react";
import { FaReact, FaNodeJs, FaVuejs, FaHtml5, FaMoneyBillWave, FaLayerGroup, FaDocker, FaRobot, FaMarkdown } from "react-icons/fa";
import {
    SiTypescript,
    SiJavascript,
    SiNestjs,
    SiSupabase,
    SiTailwindcss,
    SiNextdotjs,
    SiVite,
    SiReactrouter,
    SiExpress,
    SiGooglegemini,
    SiMongodb,
    SiJest,
    SiReacthookform,
    SiZod,
    SiClaude,
} from "react-icons/si";

export const techIcons: Record<string, ReactNode> = {
    "Next.js 16": <SiNextdotjs size={16} />,
    TypeScript: <SiTypescript size={16} />,
    Supabase: <SiSupabase size={16} />,
    "Tailwind v4": <SiTailwindcss size={16} />,
    TailwindCSS: <SiTailwindcss size={16} />,
    Zustand: <FaLayerGroup size={16} />,
    Asaas: <FaMoneyBillWave size={16} />,
    "React 18": <FaReact size={16} />,
    "React.js": <FaReact size={16} />,
    Vite: <SiVite size={16} />,
    "React Router": <SiReactrouter size={16} />,
    JavaScript: <SiJavascript size={16} />,
    "Node.js": <FaNodeJs size={16} />,
    NestJS: <SiNestjs size={16} />,
    "Vue.js": <FaVuejs size={16} />,
    "HTML5 & CSS3": <FaHtml5 size={16} />,
    React: <FaReact size={16} />,
    Express: <SiExpress size={16} />,
    Gemini: <SiGooglegemini size={16} />,
    MongoDB: <SiMongodb size={16} />,
    Docker: <FaDocker size={16} />,
    Jest: <SiJest size={16} />,
    "React Hook Form": <SiReacthookform size={16} />,
    Zod: <SiZod size={16} />,
    "Claude Skills": <SiClaude size={16} />,
    "IA aplicada": <FaRobot size={16} />,
    Markdown: <FaMarkdown size={16} />,
};
